name: update flake inputs
on:
  schedule:
    - cron: "0 3 * * *" # nightly at 03:00 UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: update flake inputs
        env:
          GITEA_TOKEN: ${{ secrets.TOKEN }}
        run: |
          nix run \
            "github:Mic92/update-flake-inputs-gitea" -- \
            --gitea-url "https://codeberg.org" \
            --gitea-repository "${{ forgejo.repository }}" \
            --base-branch "main" \
            --git-author-name "nixfiles-bot" \
            --git-author-email "nixfiles-bot@noreply.codeberg.org" \
            --git-committer-name "nixfiles-bot" \
            --git-committer-email "nixfiles-bot@noreply.codeberg.org" \
            --auto-merge
